### ISSUE TITLE
Document differences between the HTTP fault injection for PodDisruptor and ServiceDisrupors

### ISSUE THREAD

**Issue by pablochacin** [grafana/xk6-disruptor#122]
The documentation for the `injectHTTPFaults` methods for the [PodDisruptor](https://k6.io/docs/javascript-api/xk6-disruptor/api/poddisruptor/injecthttpfaults/) and [ServiceDisruptor](https://k6.io/docs/javascript-api/xk6-disruptor/api/servicedisruptor/injecthttpfaults/) do not explain these two methods' differences in treating the `port` parameter in the [httpFault](https://k6.io/docs/javascript-api/xk6-disruptor/api/faults/http/).

The `PodDisruptor` interprets the `port` parameter as the `container port` in the Pod while the `ServiceDisruptor` Interprets the `port` as the `port` in the Service. In many cases, these two interpretations correspond, as the service's port matches the pod's container port.  But this is not always the case.  

To better understand the issue, consider the following example of a pod exposed as a service. Notice the pod exposes port `80` while the service exposes port `8080` and maps it to port `80` in the Pod.

Pod:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
```

Service:

 ```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports: 
  - port: 8080
    targetPort: 80
  selector:
    app: nginx
```
 
 Consider now the following `HttpFault` definition:
 ```json
 {
   port: 80
   errorRate: 0.1
   error: 500
 }
```

If this fault is injected using a PodDisruptor, the results are as expected: the traffic to the Pod's port 80 is disrupted. If applied to a ServiceDisruptor, we get: `error injecting fault: the service does not expose the given port: 80`.

To make this fault work for a service disruptor, we must change the `port` to `8080`.
