### ISSUE TITLE
ServiceDisruptor does not resolve target port if service uses port name

### ISSUE THREAD

**Issue by pablochacin** [grafana/xk6-disruptor#130]
If a service specifies the target port using its name, the ServiceDisruptor is not able to resolve it. As a result, the agent uses the default target port (80). 

How to reproduce: 

1. Deploy a pod that exposes port `8080` with the name `http`.
2. Expose the pod with a port that maps port 80 to the target port `http`
3. Inject faults to port 80 of the service using a ServiceDisruptor. The faults are not injected, because the disruptor will use the default target port 80 in the pod, instead of the exposed port 8080.

See the manifest below for deploying and exposing the pod and the script for injecting faults.

<details>
 <summary>Manifests</summary>

```yaml
kind: Service
apiVersion: v1
metadata:
  name: httpbin
  namespace: httpbin
spec:
  selector:
      app: httpbin
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: HTTP
----
kind: Namespace
apiVersion: v1
metadata:
  name: httpbin
---
kind: Pod
apiVersion: v1
metadata:
  name: httpbin
  namespace: httpbin
  labels:
     app: httpbin
spec:
  containers:
  - name: httpbin
    image: mccutchen/go-httpbin
    command: ["go-httpbin", "--port", "8080"]
    ports:
    - name: http
      containerPort: 8080
```

</details>

<details>
 <summary>Tesscript</summary>

```javascript
import { ServiceDisruptor } from 'k6/x/disruptor';
import http from 'k6/http';

export default function (data) {
    http.get(`http://${__ENV.SVC_IP}/status/200`);
}

export function disrupt(data) {
    if (__ENV.SKIP_FAULTS == "1") {
        return
    }

    const disruptor = new ServiceDisruptor("httpbin", "httpbin")

    // delay traffic from one random replica of the deployment
    const fault = {
        port: 80,
        averageDelay: 200,
        errorCode: 500,
        errorRate: 0.1
    }
    const opts = {
            proxyPort: 8000
    }
    disruptor.injectHTTPFaults(fault, 30, opts)
}

export const options = {
    scenarios: {
        load: {
            executor: 'constant-arrival-rate',
            rate: 100,
            preAllocatedVUs: 10,
            maxVUs: 100,
            exec: "default",
            startTime: '0s',
            duration: "30s",
        },
        disrupt: {
            executor: 'shared-iterations',
            iterations: 1,
            vus: 1,
            exec: "disrupt",
            startTime: "0s",
        },
    }
}
```
</details>
