### ISSUE TITLE
Use memory storage for etcd in e2d2 test clusters

### ISSUE THREAD

**Issue by pablochacin** [grafana/xk6-disruptor#179]
etcd is [a well know source  of overhead](https://github.com/kubernetes-sigs/kind/issues/845#issuecomment-1261248420) when running test clusters with kind. 

The most [common approach ](https://github.com/kubernetes-sigs/kind/issues/845#issuecomment-1261248420 ) is to use `tmpfs` for the etcd database:

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
- |
  kind: ClusterConfiguration
  etcd:
    local:
      dataDir: /tmp/etcd     # /tmp is mapped to tmpfs in kind's nodes
```

This configuration option could be added to the e2ecluster to enable faster cluster operation.
