### ISSUE TITLE
no Auth Provider found for name "oidc"

### ISSUE THREAD

**Issue by Ugzuzg** [grafana/xk6-disruptor#412]
I get the following error while trying to `xk6-disruptor run script.js`:

```
ERRO[0000] GoError: error creating Kubernetes helper: no Auth Provider found for name "oidc"
        at go.k6.io/k6/js.(*requireImpl).require-fm (native)
```

The user config has the same shape as in [this example](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#option-1-oidc-authenticator):

```yaml
users:
- name: mmosley
  user:
    auth-provider:
      config:
        client-id: kubernetes
        client-secret: secret
        id-token: token
        idp-certificate-authority: /root/ca.pem
        idp-issuer-url: https://oidcidp.tremolo.lan:8443/auth/idp/OidcIdP
        refresh-token: refresh-token
      name: oidc
```

A possibly relevant issue: https://github.com/fluxcd/terraform-provider-flux/issues/669. They fixed it by simply importing `k8s.io/client-go/plugin/pkg/client/auth`.
